name: amnak
description: A new Flutter template.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.4.0

  animated_custom_dropdown: ^3.0.0
  local_auth: ^2.3.0
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  multi_select_flutter: ^4.1.3
  image_picker: ^1.0.6
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  lottie: ^2.7.0
  file_picker: ^8.1.6
  equatable: ^2.0.5
  go_router: ^13.2.2
  flutter_bloc: ^8.1.3
  internet_connection_checker: ^1.0.0+1
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  get_it: ^7.6.6
  iconify_flutter: ^0.0.7
  flutter_svg:
  google_fonts: 6.1.0
  flutter_html: ^3.0.0-beta.2
  font_awesome_flutter: ^10.8.0
  flutter_secure_storage: ^9.1.1
  intl: ^0.19.0
  infinite_scroll_pagination: ^3.2.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.1
  agora_rtc_engine: ^6.5.0
  permission_handler: ^11.3.1
  provider: ^6.1.5
  fluttertoast: ^8.2.12
  record: ^6.0.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  logger: ^2.0.2+1
  rename_app: ^1.3.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  # HTTP Inspector tool for Flutter which helps debugging http requests.
  requests_inspector: ^4.2.0
  flutter_lints:
  mocktail: ^1.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  build_runner: ^2.4.5
  freezed: ^2.3.2
  json_serializable: ^6.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/anim/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/
  filename: assets.dart
  field_prefix:

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBOld.ttf
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
